###

POST http://localhost:8080/jobs
Content-Type: application/json

{
  "jobName": "greetingJob",
  "jobParameters": {
    "timeout": 5000
  }
}

###

POST http://localhost:8081/jobs
Content-Type: application/json

{
  "jobName": "printJob",
  "jobParameters": {
    "timeout": 5000
  }
}

###

POST http://localhost:8080/jobs/1/stop

###

POST http://localhost:8080/jobs/1/restart


###

GET http://localhost:8080/jobs/1
