###

POST http://localhost:8080/jobs
Content-Type: application/json

{
  "jobName": "greetingJob",
  "jobParameters": {
    "greetingName": "Mario",
    "timeout": 5011
  }
}
###


POST http://localhost:8080/jobs
Content-Type: application/json

{
  "jobName": "greetingJob",
  "jobParameters": {
    "greetingName": "Mario",
    "timeout": 510008
  }
}

> {%
    client.global.set("externalJobExecutionId", response.body.externalJobExecutionId)
%}

###

POST http://localhost:8080/jobs/{{externalJobExecutionId}}/restart

###

POST http://localhost:8080/jobs/{{externalJobExecutionId}}/stop

###

GET http://localhost:8080/jobs/{{externalJobExecutionId}}
