management:
  endpoints:
    web:
      exposure:
        include: '*'
    access:
      default: unrestricted
spring:
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: 'false'
  application:
    name: app-http-docker
  liquibase:
    change-log: classpath:/db/changelog.yml
    enabled: 'true'
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
server:
  port: '8080'
job:
  docker:
    configurations:
      - job-name: greetingJob
        docker-image-name: app-shell-greeting-local:latest
        docker-network-name: batch-network
        spring-application-json: >
          {
            "spring": {
              "datasource": {
                "url": "jdbc:postgresql://postgres:5432/postgres",
                "username": "postgres",
                "password": "postgres"
              }
            }
          }
