services:

  app-http-docker:
    build:
      context: ../../sample/apps/app-http-docker/
      dockerfile: Dockerfile
    image: app-http-docker
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      job.docker.configurations[0].job-name: greetingJob
      job.docker.configurations[0].docker-image-name: app-shell-greeting-local
      job.docker.configurations[0].docker-network-name: batch-network
      job.docker.configurations[0].spring-application-json: >
        {
          "spring": {
            "datasource": {
              "url": "jdbc:postgresql://postgres:5432/postgres",
              "username": "postgres",
              "password": "postgres"
            }
          }
        }
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      batch-network:

networks:
  batch-network:
      name: "batch-network"
      external: false

