apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: batch-job-runner-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: batch-job-sa
    namespace: default
roleRef:
  kind: Role
  name: batch-job-runner
  apiGroup: rbac.authorization.k8s.io