apiVersion: v1
kind: Service
metadata:
  name: app-http-kubernetes
spec:
  type: NodePort
  selector:
    app: app-http-kubernetes
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080